channels:
- conda-forge
- pytorch
- pyg
- defaults
dependencies:
- jupyter=1.0.0
- pandas=1.4.1
- pip=22.0.3
- pymongo=3.12.0
- pytorch=1.11.0
- pytorch-scatter=2.0.9
- pyyaml=6.0
- scikit-learn=1.0.2
- torchaudio=0.11.0
- torchvision=0.12.0
- tqdm=4.62.3
- python=3.9
- pip:
  - interchange==2021.0.4
  - monotonic==1.6
  - neo4j==4.4.1
  - ordered-set==4.1.0
  - pansi==2020.7.3
  - py2neo==2021.2.3
  - pytz==2021.3
  - mlflow
  - kaleido
  - optuna
  - pyvis
  - networkx==2.6.1
name: GNNRS
